# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);



###  댓글 추가기능
POST http://localhost:8080/replies
Content-Type: application/json

{
"bno":"4",
"replytext":"댓글을 추가합니다.ㄴㅇㄹ!",
"replyer":"user00"
}


### 댓글 갯수 확인
GET http://localhost:8080/replies/all/4
###

###  댓글   번호로  수정 http://localhost:8080/replies/{rno}
PUT http://localhost:8080/replies/6
Content-Type: application/json

{
"replytext":" 수정합니다.12312312",
"replyer":"user00"
}



### 댓글 삭제 http://localhost:8080/replies/{rno}
DELETE http://localhost:8080/replies/5
###









